(* /home/sara/Dropbox/Reaching Study/Gilwoo_Automated_v2/csv_only_manual_inspection/2016_11_24_study_4_Part3_1/2016_11_24_study_4_Part3_1_2510-2749_clean_phase2.csv*)
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
