(* /home/sara/Dropbox/Reaching Study/Gilwoo_Automated_v2/csv_only_manual_inspection/2016_12_14_study_4_Part9_2/2016_12_14_study_4_Part9_2_38812_39041_clean_phase1.csv*)
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
